=== STFCcommunity/data/schemas/systems.json
{
  "$id": "http://example.com/example.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "The root schema",
  "description": "A schema for systems in STFC",
  "required": [
    "name",
    "connected_systems",
    "faction",
    "level",
    "scopely_id",
    "system_space",
    "system_type",
    "warp"
  ],
  "type": "object",
  "additionalProperties": true,
  "default": {},
  "examples": [
    {
      "name": "P'Jem",
      "capture_nodes": 0,
      "connected_systems": [
        {
          "$ref": "systems/aiti_33"
        },
        {
          "$ref": "systems/andoria_34"
        },
        {
          "$ref": "systems/doska_27"
        },
        {
          "$ref": "systems/losti_28"
        },
        {
          "$ref": "systems/noakyn_30"
        },
        {
          "$ref": "systems/spira_27"
        },
        {
          "$ref": "systems/tau_ceti_34"
        }
      ],
      "faction": "federation",
      "hub_details": {
        "hub_number": 5,
        "hub_size": 5
      },
      "level": 29,
      "mining": [
        {
          "type": "gas",
          "amount": 24,
          "grade": 3,
          "mining_per_hour": 300,
          "size": 18000
        }
      ],
      "planets": [
        "Bexeiug",
        "Fanux",
        "P'Jem",
        "Puqaxuo",
        "Xeuuair",
        "Zizub"
      ],
      "scopely_id": 468245102,
      "system_space": "normal",
      "system_type": "hub",
      "warp": 20
    }
  ],
  "properties": {
    "name": {
      "$id": "#/properties/name",
      "title": "The name schema",
      "description": "The system name",
      "type": "string",
      "default": "",
      "examples": [
        "P'Jem"
      ]
    },
    "capture_nodes": {
      "$id": "#/properties/capture_nodes",
      "title": "The capture_nodes schema",
      "description": "The number of capture nodes present in this system",
      "type": "integer",
      "default": 0,
      "examples": [
        0
      ]
    },
    "connected_systems": {
      "$id": "#/properties/connected_systems",
      "title": "The connected_systems schema",
      "description": "Other systems this system is connected to",
      "type": "array",
      "additionalItems": true,
      "default": [],
      "examples": [
        [
          {
            "$ref": "systems/aiti_33"
          },
          {
            "$ref": "systems/andoria_34"
          }
        ]
      ],
      "items": {
        "$id": "#/properties/connected_systems/items",
        "anyOf": [
          {
            "$id": "#/properties/connected_systems/items/anyOf/0",
            "title": "The first anyOf schema",
            "description": "The reference to a connected system",
            "required": [
              "$ref"
            ],
            "type": "object",
            "additionalProperties": true,
            "default": {},
            "examples": [
              {
                "$ref": "systems/aiti_33"
              }
            ],
            "properties": {
              "$ref": {
                "$id": "#/properties/connected_systems/items/anyOf/0/properties/%24ref",
                "title": "The $ref schema",
                "description": "The reference to a system name in the form systems/<system_name>_<system_level>",
                "type": "string",
                "default": "",
                "examples": [
                  "systems/aiti_33"
                ]
              }
            }
          }
        ]
      }
    },
    "faction": {
      "$id": "#/properties/faction",
      "title": "The faction schema",
      "description": "The faction this system belongs to",
      "type": "string",
      "default": "",
      "examples": [
        "federation"
      ]
    },
    "hub_details": {
      "$id": "#/properties/hub_details",
      "title": "The hub_details schema",
      "description": "Details about the hubs in this system.",
      "required": [
        "hub_number",
        "hub_size"
      ],
      "type": "object",
      "additionalProperties": true,
      "default": {},
      "examples": [
        {
          "hub_number": 5,
          "hub_size": 5
        }
      ],
      "properties": {
        "hub_number": {
          "$id": "#/properties/hub_details/properties/hub_number",
          "title": "The hub_number schema",
          "description": "The number of hubs present in this system",
          "type": "integer",
          "default": 0,
          "examples": [
            5
          ]
        },
        "hub_size": {
          "$id": "#/properties/hub_details/properties/hub_size",
          "title": "The hub_size schema",
          "description": "The size of each hub.",
          "type": "integer",
          "default": 0,
          "examples": [
            5
          ]
        }
      }
    },
    "level": {
      "$id": "#/properties/level",
      "title": "The level schema",
      "description": "The system level",
      "type": "integer",
      "default": 1,
      "examples": [
        29
      ]
    },
    "mining": {
      "$id": "#/properties/mining",
      "title": "The mining schema",
      "description": "Details about the mines present in this system",
      "type": "array",
      "additionalItems": true,
      "default": [],
      "examples": [
        [
          {
            "type": "gas",
            "amount": 24,
            "grade": 3,
            "mining_per_hour": 300,
            "size": 18000
          }
        ]
      ],
      "items": {
        "$id": "#/properties/mining/items",
        "anyOf": [
          {
            "$id": "#/properties/mining/items/anyOf/0",
            "title": "The first anyOf schema",
            "description": "For each type of mine present",
            "required": [
              "type",
              "amount",
              "mining_per_hour",
              "size"
            ],
            "type": "object",
            "additionalProperties": true,
            "default": {},
            "examples": [
              {
                "type": "gas",
                "amount": 24,
                "grade": 3,
                "mining_per_hour": 300,
                "size": 18000
              }
            ],
            "properties": {
              "type": {
                "$id": "#/properties/mining/items/anyOf/0/properties/type",
                "title": "Type of resource gained",
                "description": "An explanation about the purpose of this instance.",
                "type": "string",
                "default": "",
                "examples": [
                  "gas"
                ]
              },
              "amount": {
                "$id": "#/properties/mining/items/anyOf/0/properties/amount",
                "title": "The amount schema",
                "description": "Number of mines present",
                "type": "integer",
                "default": 0,
                "examples": [
                  24
                ]
              },
              "grade": {
                "$id": "#/properties/mining/items/anyOf/0/properties/grade",
                "title": "The grade schema",
                "description": "The grade of raw materials in the mines",
                "type": "integer",
                "default": 0,
                "examples": [
                  3
                ]
              },
              "mining_per_hour": {
                "$id": "#/properties/mining/items/anyOf/0/properties/mining_per_hour",
                "title": "The mining_per_hour schema",
                "description": "Speed of the mining",
                "type": "integer",
                "default": 0,
                "examples": [
                  300
                ]
              },
              "size": {
                "$id": "#/properties/mining/items/anyOf/0/properties/size",
                "title": "The size schema",
                "description": "The size of a full mine",
                "type": "integer",
                "default": 0,
                "examples": [
                  18000
                ]
              }
            }
          }
        ]
      }
    },
    "planets": {
      "$id": "#/properties/planets",
      "title": "The planets schema",
      "description": "Planets present in this system",
      "type": "array",
      "additionalItems": true,
      "default": [],
      "examples": [
        [
          "Bexeiug",
          "Fanux"
        ]
      ],
      "items": {
        "$id": "#/properties/planets/items",
        "anyOf": [
          {
            "$id": "#/properties/planets/items/anyOf/0",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "type": "string",
            "default": "",
            "examples": [
              "Bexeiug",
              "Fanux"
            ]
          }
        ]
      }
    },
    "scopely_id": {
      "$id": "#/properties/scopely_id",
      "title": "The scopely_id schema",
      "description": "In-Game numeric reference to this system",
      "type": "integer",
      "default": 0,
      "examples": [
        468245102
      ]
    },
    "system_space": {
      "$id": "#/properties/system_space",
      "title": "The system_space schema",
      "description": "The type of space this system can belong to",
      "type": "string",
      "default": "",
      "enum": [
        "normal",
        "origin",
        "deep",
        "dark"
      ],
      "examples": [
        "normal"
      ]
    },
    "system_type": {
      "$id": "#/properties/system_type",
      "title": "The system_type schema",
      "description": "Hub systems interconnect multiple systems, terminal have only one warp path",
      "type": "string",
      "default": "",
      "enum": [
        "hub",
        "terminal",
        "route"
      ],
      "examples": [
        "hub"
      ]
    },
    "token_info": {
      "$id": "#/properties/token_info",
      "title": "The token_info schema",
      "description": "Detailed information about the token needed.",
      "required": [
        "token_type",
        "token_amount"
      ],
      "type": "object",
      "additionalProperties": true,
      "default": {},
      "properties": {
        "token_amount": {
          "$id": "#/properties/token_info/properties/token_amount",
          "title": "The token_amount schema",
          "description": "Amount of tokens needed for accessing this system.",
          "type": "integer",
          "default": 0,
          "examples": [
            1
          ]
        },
        "token_type": {
          "$id": "#/properties/token_info/properties/token_type",
          "title": "The token_type schema",
          "description": "The name of the token needed",
          "type": "string",
          "default": "",
          "examples": [
            "Very rare token for very expensive things"
          ]
        }
      }
    },
    "token_needed": {
      "$id": "#/properties/token_needed",
      "title": "The token_needed schema",
      "description": "Is a token needed for accessing this system.",
      "type": "boolean",
      "default": false,
      "examples": [
        false
      ]
    },
    "warp": {
      "$id": "#/properties/warp",
      "title": "The warp schema",
      "description": "Warp needed from a lvl1 system",
      "type": "integer",
      "default": 0,
      "examples": [
        20
      ]
    }
  }
}

=== STFCcommunity/data/systems/holles_43.json
{
  "name": "Holles",
  "capture_nodes": 0,
  "connected_systems": [
    {
      "$ref": "systems/almango_43"
    },
    {
      "$ref": "systems/hyland_42"
    },
    {
      "$ref": "systems/kildare_43"
    },
    {
      "$ref": "systems/luoman_41"
    },
    {
      "$ref": "systems/new_calgary_43"
    },
    {
      "$ref": "systems/new_canberra_44"
    },
    {
      "$ref": "systems/rua_ri_42"
    }
  ],
  "faction": "federation",
  "level": 43,
  "mining": [
    {
      "type": "gas",
      "amount": 12,
      "grade": 4,
      "mining_per_hour": 300,
      "size": 89076
    }
  ],
  "planets": [
    "Starbase 87"
  ],
  "scopely_id": 1702244411,
  "system_space": "deep",
  "system_type": "hub",
  "warp": 75
}

=== STFCcommunity/data/systems/benes_delta_27.json
{
  "name": "Benes Delta",
  "capture_nodes": 0,
  "connected_systems": [
    {
      "$ref": "systems/pasadoran_26",
      "distance": 18,
      "warp": 18
    }
  ],
  "faction": "neutral",
  "level": 27,
  "mining": [],
  "planets": [
    "Dahlman",
    "Koalar",
    "Olltala",
    "Pear"
  ],
  "scopely_id": 2124972704,
  "system_space": "normal",
  "system_type": "terminal",
  "token_info": {
    "type": "item",
    "token_amount": 1,
    "token_type": "Transwarp Cell"
  },
  "token_needed": true,
  "warp": 18
}

=== STFCcommunity/data/systems/hsp_g_40.json
{
  "name": "HSP-G",
  "capture_nodes": 0,
  "connected_systems": [
    {
      "$ref": "systems/pneuma_40",
      "warp": 70
    },
    {
      "$ref": "systems/rowla_40",
      "warp": 1
    }
  ],
  "faction": "neutral",
  "level": 40,
  "mining": [],
  "scopely_id": 1141745487,
  "system_space": "deep",
  "system_type": "route",
  "warp": 64
}

=== STFCcommunity/data/systems/jeuaiei_25.json
{
  "name": "Jeuaiei",
  "capture_nodes": 0,
  "connected_systems": [
    {
      "$ref": "systems/vendus_a_27"
    }
  ],
  "faction": "romulan",
  "hub_details": {
    "hub_number": 10,
    "hub_size": 16
  },
  "level": 25,
  "mining": [
    {
      "type": "parsteel",
      "amount": 25,
      "mining_per_hour": 1200,
      "size": 60000
    }
  ],
  "planets": [
    "Audonuf",
    "Bauuk",
    "Fipelih",
    "Gexufak",
    "Iifok",
    "Juoek",
    "Kaeaw",
    "Mumaper",
    "Oimin",
    "Sewiaeb",
    "Vouukab"
  ],
  "scopely_id": 1556190441,
  "system_space": "normal",
  "system_type": "terminal",
  "warp": 19
}

=== STFCcommunity/data/systems/dela_51.json
{
  "name": "Dela",
  "capture_nodes": 0,
  "connected_systems": [
    {
      "$ref": "systems/remme_50",
      "distance": 30,
      "warp": 185
    },
    {
      "$ref": "systems/farana_50",
      "distance": 30,
      "warp": 105
    },
    {
      "$ref": "systems/tej_lukk_50",
      "distance": 1,
      "warp": 185
    },
    {
      "$ref": "systems/belmont_51",
      "distance": 205,
      "warp": 205
    },
    {
      "$ref": "systems/ghuh_50",
      "distance": 185,
      "warp": 185
    }
  ],
  "faction": "neutral",
  "level": 51,
  "mining": [],
  "planets": [
    "Dayon-C",
    "Dela Prime",
    "Shelly"
  ],
  "scopely_id": 393023826,
  "system_space": "deep",
  "system_type": "hub",
  "warp": 185
}

=== STFCcommunity/data/systems/nelvana_32.json
{
  "name": "Nelvana",
  "capture_nodes": 0,
  "connected_systems": [
    {
      "$ref": "systems/calder_39",
      "distance": 31,
      "warp": 31
    },
    {
      "$ref": "systems/azati_34",
      "distance": 25,
      "warp": 27
    },
    {
      "$ref": "systems/gradientes_30",
      "distance": 27,
      "warp": 24
    }
  ],
  "faction": "romulan",
  "level": 32,
  "mining": [
    {
      "type": "Dilithium",
      "amount": 5,
      "mining_per_hour": 80,
      "size": 8000
    }
  ],
  "planets": [
    "Nelvana I",
    "Nelvana II"
  ],
  "scopely_id": 37,
  "system_space": "normal",
  "system_type": "hub",
  "warp": 27
}

=== STFCcommunity/data/systems/saetel_46.json
{
  "name": "Saetel",
  "capture_nodes": 0,
  "connected_systems": [
    {
      "$ref": "systems/bildari_44",
      "distance": 120,
      "warp": 95
    },
    {
      "$ref": "systems/tulris_48",
      "distance": 150,
      "warp": 150
    }
  ],
  "faction": "romulan",
  "level": 46,
  "mining": [],
  "planets": [],
  "scopely_id": 1383541989,
  "system_space": "normal",
  "system_type": "route",
  "warp": 120
}

=== STFCcommunity/data/systems/kol_ran_22.json
{
  "name": "Kol Ran",
  "capture_nodes": 0,
  "connected_systems": [
    {
      "$ref": "systems/francihk_20",
      "distance": 15,
      "warp": 13
    },
    {
      "$ref": "systems/urthak_26",
      "distance": 16,
      "warp": 16
    }
  ],
  "faction": "klingon",
  "level": 22,
  "mining": [],
  "planets": [
    "Auoiq",
    "Feyaxev",
    "Iaiun",
    "Ionuqiy",
    "Koyir",
    "Yaoelel",
    "Yebiv",
    "Zafaeue"
  ],
  "scopely_id": 395344716,
  "system_space": "normal",
  "system_type": "route",
  "warp": 15
}
